Document: metagoofil
Title: Debian metagoofil Manual
Author: <insert document author here>
Abstract: This manual describes what metagoofil is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/metagoofil/metagoofil.sgml.gz

Format: postscript
Files: /usr/share/doc/metagoofil/metagoofil.ps.gz

Format: text
Files: /usr/share/doc/metagoofil/metagoofil.text.gz

Format: HTML
Index: /usr/share/doc/metagoofil/html/index.html
Files: /usr/share/doc/metagoofil/html/*.html
